efaults:
  - override hydra/job_logging: default
  - override hydra/launcher: basic

#hydra:
#  mode: MULTIRUN
#  job_logging: {}
#  hydra_logging: {}
#  sweeper:
#    params:
#      experiment.learnable_std: true, false
#      experiment.init_std: 0.1, 0.2
#      experiment.num_steps: 10, 20
#      experiment.update_epochs: 4
#      experiment.clip_eps: 0.2, 0.05
#      # env_params
#      experiment.env_params.env_name: MjxUnitreeH1.walk, MjxUnitreeH1.run

wandb:
  project: "unitreeGo2"

experiment:
  task_factory:
    name: RLFactory
    params: {}
  env_params:
    env_name: MjxBerkeleyHumanoidLite
    horizon: 1000
    terminal_state_type: HeightBasedTerminalStateHandler
    goal_type: GoalRandomRootVelocity
    goal_params:
      visualize_goal: true
    headless: true
    reward_type: LocomotionReward
    reward_params:
      tracking_w_exp_xy: 4.0
      tracking_w_exp_yaw: 4.0
      tracking_w_sum_xy: 2.0
      tracking_w_sum_yaw: 1.0
      air_time_coeff: 0.1
      joint_acc_coeff: 2.0e-05
      air_time_max: 0.5
      joint_torque_coeff: 2.0e-07
      joint_position_limit_coeff: 2.0
      action_rate_coeff: 0.1
      symmetry_air_coeff: 0.0
      energy_coeff: 5.0e-05
      foot_contact_sites: ["left_foot_mimic", "right_foot_mimic"]
  hidden_layers: [512, 256]
  lr: 1e-4
  num_envs: 2048
  num_steps: 50
  total_timesteps: 10e7
  update_epochs: 4
  num_minibatches: 32
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  init_std: 0.8
  learnable_std: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  activation: tanh
  anneal_lr: false
  weight_decay: 0.0
  normalize_env: true
  debug: false
  n_seeds: 1  # while automatically take seeds from 1 to n_seeds
  vmap_across_seeds: true
  validation:
    active: false
    num_steps: 100
    num_envs: 100
    num: 10 # set to 0 to disable validation